spring.datasource.url= ${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username= ${DATABASE_USERNAME}
spring.datasource.password= ${DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
logging.level.org.springframework.web=DEBUG
logging.level.com.financeai=TRACE
logging.level.org.springframework.web.servlet=TRACE
app.jwt.secret=${JWT_SECRET}
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
server.error.whitelabel.enabled=false

# VARIÁVEIS PARA O BANCO NA NUVEM (SUGESTÃO)
# PARA USAR O BANCO NA NUVEM, DESCOMENTE AS LINHAS ABAIXO E COMENTE AS LINHAS DE CONFIGURAÇÃO COM O MESMO NOME ACIMA
# LEMBRE DE COLOCAR OS VALORES NO .ENV ;)

#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.jpa.hibernate.ddl-auto=validate

# VARIÁVEIS PARA O BANCO NA NUVEM (SUGESTÃO)
# PARA USAR O BANCO NA NUVEM, DESCOMENTE AS LINHAS ABAIXO E COMENTE AS LINHAS DE CONFIGURAÇÃO COM O MESMO NOME ACIMA
# LEMBRE DE COLOCAR OS VALORES NO .ENV ;)

#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.jpa.hibernate.ddl-auto=validate