spring.datasource.url=jdbc:h2:mem:financeai;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.main.allow-circular-references=true
logging.level.org.springframework.web=DEBUG
logging.level.com.financeai=TRACE
logging.level.org.springframework.web.servlet=TRACE
app.jwt.secret=financeai-secret-key-super-segura-2024-hackathon-elas-tech-256bits-ok

# VARIÁVEIS PARA O BANCO NA NUVEM (SUGESTÃO)
# PARA USAR O BANCO NA NUVEM, DESCOMENTE AS LINHAS ABAIXO E COMENTE AS LINHAS DE CONFIGURAÇÃO COM O MESMO NOME ACIMA
# LEMBRE DE COLOCAR OS VALORES NO .ENV ;)

#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.jpa.hibernate.ddl-auto=validate